PokemonTCG/config/routes.rb
Rails.application.routes.draw do
  resources :decks
  resources :cards
  resources :users

  get '/login', to: 'users#display_login_form'
  post '/users/authenticate', to: 'users#authenticate'

  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

PokemonTCG/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

PokemonTCG/app/models/card.rb
class Card < ApplicationRecord
    belongs_to :user
    belongs_to :deck
    
end

PokemonTCG/app/models/deck.rb
class Deck < ApplicationRecord
    has_many :cards
    has_many :users, through: :cards
end

PokemonTCG/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :cards
    has_many :decks, through: :cards

end

PokemonTCG/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

PokemonTCG/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]


  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:name, :move, :poke_type, :number, :user_id, :deck_id)
    end
end

PokemonTCG/app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy]

  # GET /decks
  # GET /decks.json
  def index
    @decks = Deck.all
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url, notice: 'Deck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deck_params
      params.require(:deck).permit(:set_name, :release_date)
    end
end

PokemonTCG/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def if
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  
  end

  # GET /users/new
  def new
  end

  # GET /users/1/edit
  def edit
  end

  #GET /users/login
  def display_login_form

  end

  #POST /users/authenticate
  def authenticate
    user = User.find_by(email: params[:email])
    if user != nil && user.authenticate(params[:password])
      session[:user_id] = user.id
      # '/users/:id'
      redirect_to "/users/#{user.id}"
    else
       flash.now[:danger] = 'Invalid'
       render 'display_login_form'
    end
  end

   def profile
       redirect_to 
   end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password_digest, :username)
    end
end

PokemonTCG/app/helpers/application_helper.rb
module ApplicationHelper
end

PokemonTCG/app/helpers/cards_helper.rb
module CardsHelper
end

PokemonTCG/app/helpers/decks_helper.rb
module DecksHelper
end

PokemonTCG/app/helpers/users_helper.rb
module UsersHelper
end

PokemonTCG/app/views/cards/_form.html.erb
<style>
.container{
  background-color: #cfcfd1;
  text-align: center;
}
</style>

<div class="container">
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field" type="number" min="0">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :move %>
    <%= form.text_field :move %>
  </div>

  <div class="field">
    <%= form.label :poke_type %>
    <%= form.text_field :poke_type %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field" type="number" min="0">
    <%= form.label :deck_id %>
    <%= form.number_field :deck_id %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

</div>

PokemonTCG/app/views/cards/edit.html.erb
<h1>Editing Card</h1>


<%= render 'form', card: @card %>
<%= render 'layouts/navbar'%>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

PokemonTCG/app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'layouts/navbar'%>

<style>
.container{
  text-align: center;
  background-color: #cfcfd1;
}
</style>

<div class="container">
<h1 class="center ">All Cards</h1>

<table class="center">
  <thead>
    <tr>
      <th>Name</th>
       <th></th>
      <th>Move</th>
      <th></th>
      <th>Species</th>
      <th></th>
      <th>Pokédex Number</th>
      <th></th>
      <th>User</th>
      <th></th>
      <th>Deck</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.name %></td>
         <td><%=  %></td>
        <td><%= card.move %></td>
        <td><%=  %></td>
        <td><%= card.poke_type %></td>
        <td><%=  %></td>
        <td><%= card.number %></td>
        <td><%=  %></td>
        <td><%= card.user_id %></td>
        <td><%=  %></td>
        <td><%= card.deck_id %></td>
        <td><%=  %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Custom Card', new_card_path %>
</div>

PokemonTCG/app/views/cards/new.html.erb
<h1>Custom Card</h1>


<%= render 'form', card: @card %>
<%= link_to 'Back', cards_path %>
<%= render 'layouts/navbar'%>

PokemonTCG/app/views/cards/show.html.erb
<%= render 'layouts/navbar'%>

<style>
.container{
    background-color: #cfcfd1;
}
</style>

<div class="center container">
<%=image_tag "#{@card.url}" %>
<br>
<div class="center text-align border: 2px solid black">
<h3 class="center">
<strong>Species:</strong>
<%= @card.poke_type %>
</h3>
<br>
<h3 class="center">
<strong>User:</strong>
<%= @card.user_id %>
</h3>
<br>
<h3 class="center">
<strong>Deck:</strong>
<%= @card.deck_id %>
</h3>


<div class="center">
<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>
</div>
</div>
</div>

PokemonTCG/app/views/decks/_form.html.erb
<%= render 'layouts/navbar'%>
<%= form_with(model: deck, local: true) do |form| %>
  <% if deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% deck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :set_name %>
    <%= form.text_field :set_name %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.text_field :release_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

PokemonTCG/app/views/decks/edit.html.erb
<h1>Editing Deck</h1>

<%= render 'form', deck: @deck %>
<%= render 'layouts/navbar'%>

<%= link_to 'Show', @deck %> |
<%= link_to 'Back', decks_path %>

PokemonTCG/app/views/decks/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'layouts/navbar'%>

<h1>Decks</h1>

<table>
  <thead>
    <tr>
      <th>Set name</th>
      <th>Release date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @decks.each do |deck| %>
      <tr>
        <td><%= deck.set_name %></td>
        <td><%= deck.release_date %></td>
        <td><%= link_to 'Show', deck %></td>
        <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
        <td><%= link_to 'Destroy', deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deck', new_deck_path %>

PokemonTCG/app/views/decks/new.html.erb
<h1>New Deck</h1>

<%= render 'form', deck: @deck %>
<%= render 'layouts/navbar'%>

<%= link_to 'Back', decks_path %>

PokemonTCG/app/views/decks/show.html.erb
<p id="notice"><%= notice %></p>
<%= render 'layouts/navbar'%>

<p>
  <strong>Set name:</strong>
  <%= @deck.set_name %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @deck.release_date %>
</p>

<%= link_to 'Edit', edit_deck_path(@deck) %> |
<%= link_to 'Back', decks_path %>

PokemonTCG/app/views/layouts/_navbar.html.erb
<body>
<style>

</style>


  <nav class="navbar navbar-dark bg-primary navbar-expand-md fixed-top">
  <img style = "width: 5%;" src="http://pluspng.com/img-png/pokemon-logo-png-pokemon-logo-black-transparent-1600.png">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active navbar-nav mr-auto">
        <a class="nav-link" href="/users/<%=session[:user_id]%>">Profile <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active navbar-nav mr-auto">
        <a class="nav-link" href="http://localhost:3000/cards">Browse<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active navbar-nav mr-auto">
        <a class="nav-link" href="http://localhost:3000/login">Sign Out<span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>
       
     

</body>

PokemonTCG/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonTCG</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <style>
    .wat {
      padding-top: 115px;
      margin-right: 0;
    }
      .center {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 60%;
    }
    body {
    background-image: url("http://www.sclance.com/wallpapers/pokemon-backgrounds/pokemon-backgrounds_1384837.jpg");
    background-repeat: repeat;
    background-size: 105%;
    }
    h1 {
      color: black;
      text-decoration: underline;
    }
    th {
      color: black;
      text-decoration: none;
    }
    td {
      color: black;
      text-decoration: none;
    }
    a {
      color: black;
      text-decoration: none;
    }
    p {
      color: black;
      text-decoration: none;
    }
    a:visited {
    color: black;
    }
    footer {
      text-align: right;
    }
    div {
      color: black;
      text-decoration: none;
    }
  
    </style>

  </head>


  <body>
    <div class= "container margin:auto wat center ">
    
    <%= yield %>
    </div>
  </body>
  <footer>
    <p class="copyright">© Maruf & Ariq Productions 2019</p>
</footer>



</html>

PokemonTCG/app/views/users/_form.html.erb
<style>
.container{
  background-color: #cfcfd1;
  text-align: center;
}
</style>

<%= render 'layouts/navbar'%>
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

PokemonTCG/app/views/users/display_login_form.html.erb
<%= form_with method: 'POST', url: '/users/authenticate' do | form | %>

<header>
<style>
.center {
  margin: auto;
  width: 40%;
  padding: 20px;
}
.divider{
    display:inline-block;
}
</style>
</header>

<div class="container center">

<h1>Login</h1>
<body>
  <div class="row">
    <div class="Absolute-Center is-Responsive">
      <div id="logo-container"></div>
      <div class="col-sm-12 col-md-10 col-md-offset-1">
        <div>
          <div class="form-group input-group ">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user">
            <%= form.label :email %>
            <%= form.text_field :email %> 
            </i></span>        
          <div class="divider">
          <div class="form-group input-group ">
            <span class="input-group-addon"><i class="glyphicon glyphicon-lock">
             <%= form.label :password %>
            <%= form.password_field :password%>
            </i></span>
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> I agree to Catch 'Em All</input>
            </label>
          </div>

          <div class="form-group">
            <%= form.submit :Login %>
          </div>
          <div class="form-group">
            <%= form.submit :NewUser %>

          </div>
          <% end %>
      </div>  
    </div>    
  </div>
  </body>
</div>

PokemonTCG/app/views/users/edit.html.erb
<div class="container">
<h1>Editing User</h1>

<%= render 'form', user: @user %>
<%= render 'layouts/navbar'%>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
</div>

PokemonTCG/app/views/users/index.html.erb
<%= render 'layouts/navbar'%>
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

PokemonTCG/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>
<%= render 'layouts/navbar'%>

<%= link_to 'Back', users_path %>

PokemonTCG/app/views/users/show.html.erb
<style>
.container{
  background-color: #cfcfd1;
}
</style>

<%= render 'layouts/navbar'%>

<div class="container">
<p id="notice"><%= notice %></p>

<div class="center">
<h2 >
  <strong>Gotta Catch 'Em All </strong>
  <%= @user.name %>
  <strong>! </strong>
</h2>

<p>
  <strong>Trainer Email:</strong>
  <%= @user.email %>
</p>


<p>
  <strong>Trainer Name:</strong>
  <%= @user.name %>
</p>

<h2>
  <strong>Your Pokemon </strong>
  <br>
  <% @user.cards.each do |card| %>
    <%=image_tag "#{card.url_tiny}"%>
  <% end %>
</h2>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
</div>
</div>